# Generated by Django 6.0.2 on 2026-03-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_project', '0008_alter_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='radius',
            field=models.FloatField(default=100.0),
        ),
    ]
