# Generated by Django 4.2.26 on 2025-12-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'batch')},
        ),
    ]
