# Generated by Django 6.0.2 on 2026-02-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0005_merge_0003_notification_0004_auditlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
