# Generated by Django 4.2.28 on 2026-02-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0007_timetable_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
